### ISSUE TITLE
Linking fails

### ISSUE THREAD

**Issue by tindzk** [ABRG-Models/morphologica#8] opened 2020-02-18 22:47 UTC
With the latest commit, I am getting the following output under Arch Linux:

```shell
$ make
make[1]: Entering directory '/home/tim/edu/morphologica/build'
make[2]: Entering directory '/home/tim/edu/morphologica/build'
Scanning dependencies of target morphstatic
make[2]: Leaving directory '/home/tim/edu/morphologica/build'
make[2]: Entering directory '/home/tim/edu/morphologica/build'
[  1%] Building CXX object src/CMakeFiles/morphstatic.dir/display.cpp.o
[  2%] Building CXX object src/CMakeFiles/morphstatic.dir/sockserve.cpp.o
[  3%] Building CXX object src/CMakeFiles/morphstatic.dir/tools.cpp.o
[  4%] Building CXX object src/CMakeFiles/morphstatic.dir/world.cpp.o
[  5%] Building CXX object src/CMakeFiles/morphstatic.dir/ReadCurves.cpp.o
[  6%] Building CXX object src/CMakeFiles/morphstatic.dir/HexGrid.cpp.o
[  7%] Building CXX object src/CMakeFiles/morphstatic.dir/HdfData.cpp.o
[  8%] Building CXX object src/CMakeFiles/morphstatic.dir/Process.cpp.o
[  9%] Building CXX object src/CMakeFiles/morphstatic.dir/Visual.cpp.o
[ 10%] Linking CXX static library libmorphologica.a
make[2]: Leaving directory '/home/tim/edu/morphologica/build'
[ 10%] Built target morphstatic
make[2]: Entering directory '/home/tim/edu/morphologica/build'
Scanning dependencies of target morphologica
make[2]: Leaving directory '/home/tim/edu/morphologica/build'
make[2]: Entering directory '/home/tim/edu/morphologica/build'
[ 11%] Building CXX object src/CMakeFiles/morphologica.dir/display.cpp.o
[ 12%] Building CXX object src/CMakeFiles/morphologica.dir/sockserve.cpp.o
[ 13%] Building CXX object src/CMakeFiles/morphologica.dir/tools.cpp.o
[ 14%] Building CXX object src/CMakeFiles/morphologica.dir/world.cpp.o
[ 15%] Building CXX object src/CMakeFiles/morphologica.dir/ReadCurves.cpp.o
[ 16%] Building CXX object src/CMakeFiles/morphologica.dir/HexGrid.cpp.o
[ 17%] Building CXX object src/CMakeFiles/morphologica.dir/HdfData.cpp.o
[ 18%] Building CXX object src/CMakeFiles/morphologica.dir/Process.cpp.o
[ 19%] Building CXX object src/CMakeFiles/morphologica.dir/Visual.cpp.o
[ 20%] Linking CXX shared library libmorphologica.so
make[2]: Leaving directory '/home/tim/edu/morphologica/build'
[ 20%] Built target morphologica
make[2]: Entering directory '/home/tim/edu/morphologica/build'
Scanning dependencies of target testboundary
make[2]: Leaving directory '/home/tim/edu/morphologica/build'
make[2]: Entering directory '/home/tim/edu/morphologica/build'
[ 21%] Building CXX object src/CMakeFiles/testboundary.dir/testboundary.cpp.o
[ 22%] Linking CXX executable testboundary
/usr/bin/ld: libmorphologica.so: undefined reference to `wrapper2_dgemv_'
/usr/bin/ld: libmorphologica.so: undefined reference to `wrapper2_sgemv_'
/usr/bin/ld: libmorphologica.so: undefined reference to `wrapper2_sgemm_'
/usr/bin/ld: libmorphologica.so: undefined reference to `wrapper2_dgemm_'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/testboundary.dir/build.make:141: src/testboundary] Error 1
make[2]: Leaving directory '/home/tim/edu/morphologica/build'
make[1]: *** [CMakeFiles/Makefile2:322: src/CMakeFiles/testboundary.dir/all] Error 2
make[1]: Leaving directory '/home/tim/edu/morphologica/build'
make: *** [Makefile:141: all] Error 2
```

I could not find the place where these functions are referenced. Presumably, they are wrappers around LAPACK functions.

Here are the changes I have made to the build files such that CMake could find all libraries: https://github.com/ABRG-Models/morphologica/compare/master...tindzk:feat/arch-linux

**Comment by tindzk** [comment] 2020-02-18 23:15
These functions most likely come from Armadillo. I solved the linking errors by installing OpenBLAS and LAPACK from the official Arch Linux repository, as well as SuperLU and Armadillo from AUR. In my earlier CMake changes, I inadvertently dropped the Armadillo dependency which explains the linking errors. After adding `find_package (Armadillo REQUIRED)`, the project now builds successfully (see [commit](https://github.com/ABRG-Models/morphologica/commit/6919d870e647e3c1f2c4c4f491a6125af9c07f30)).

**Comment by sebjameswml** [comment] 2020-02-19 10:37
Re-opened to prompt me to check if there are any changes to the cmake files that would be useful on Arch Linux.

@tindzk can you now build morphologica on Arch with the original CMakeLists.txt files?

**Comment by sebjameswml** [comment] 2020-02-19 10:42
You also added to the readme the instructions necessary for installing dependencies on Arch Linux. I'd like to get that into the master branch, too

**Comment by tindzk** [comment] 2020-02-19 19:10
No, I could not build Morphologica with the original `CMakeLists.txt` file because I am using Arch Linux's official HDF5 and GLFW3 packages. Two changes were needed to get it to work here:

1. Link against `glfw` instead of `glfw3`
2. Replace this block for HDF5:
```cmake
  set (HDF_LIB_TYPE SHARED) # STATIC or SHARED
  string(TOLOWER ${HDF_LIB_TYPE} HDF_SEARCH_TYPE)
  find_package (HDF5 NAMES hdf5 COMPONENTS C ${HDF_SEARCH_TYPE} REQUIRED)
```
by `find_package (HDF5 REQUIRED)`.


Also, it would be good if the libjsoncpp path could be customised instead of hard-coding it to `/usr/local/lib/libjsoncpp.a`.

I am not sure how to make those CMake changes without breaking the builds on other platforms.

**Comment by sebjameswml** [comment] 2020-02-19 20:16
Thanks for the information. 

1. glfw vs glfw3. This is annoying. If you compile glfw yourself with vanilla options, the library is built as libglfw3.a/so, but OS developers install that library as libglfw.a/so. I've got different systems doing it both ways and hadn't got around to figuring out the best way to handle it in the cmake. Usually, the find_package() stuff in cmake will set some sort of cmake variable that you can use, but that doesn't seem to be the case for glfw3.

2. That little block was intended to allow me to link either static or shared hdf5. I wonder why the resulting:

```
find_package (HDF5 NAMES hdf5 COMPONENTS C SHARED REQUIRED)
```
is different from just:
```
find_package(HDF5 REQUIRED)
```

With jsoncpp, again, i don't think there is a suitable find_package() in cmake. however, jsoncpp DOES install a pkg-config file for itself. I should use that.

**Comment by tindzk** [comment] 2020-02-19 23:26
According to GLFW's [documentation](https://www.glfw.org/docs/3.0/build.html), CMake indeed defines a variable containing the library name. Using `GLFW_LIBRARIES` works when I change this block:

```cmake
if (${glfw3_FOUND})
  target_link_libraries (morphologica glfw)
endif()
```

to:

```cmake
if (${glfw3_FOUND})
  pkg_search_module(GLFW REQUIRED glfw3)
  target_link_libraries (morphologica ${GLFW_LIBRARIES})
endif()
```

Is this variable set when compiling GLFW yourself? If not, you could use `glfw3` as a fallback value.

As for HDF5, here is the output when I use `find_package (HDF5 NAMES hdf5 COMPONENTS C SHARED REQUIRED)` instead of `find_package(HDF5 REQUIRED)`:

```
-- Install prefix: /home/tim/usr
--   (This can be changed with `cmake -DCMAKE_INSTALL_PREFIX=/some/place`
-- Operating system: Linux-5.5.3-arch1-1
-- A library with LAPACK API found.
CMake Error at CMakeLists.txt:110 (find_package):
  Could not find a package configuration file provided by "HDF5" with any of
  the following names:

    hdf5Config.cmake
    hdf5-config.cmake

  Add the installation prefix of "HDF5" to CMAKE_PREFIX_PATH or set
  "HDF5_DIR" to a directory containing one of the above files.  If "HDF5"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/tim/edu/morphologica/build/CMakeFiles/CMakeOutput.log".
See also "/home/tim/edu/morphologica/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:768: cmake_check_build_system] Error 1
```

**Comment by sebjameswml** [comment] 2020-02-20 11:27
I've used your solution for glfw3, although I put the pkg_search_module() call in the top level CMakeLists.txt, along with an associated search for pkg-config itself. See if it works for you. Commit c9ca688

**Comment by sebjameswml** [comment] 2020-02-20 13:57
Commit 93cd3ad addresses HDF5, and 6a479ca attempts to find jsoncpp with pkg-config. @tindzk  can you test to see if you can build from master now?

**Comment by tindzk** [comment] 2020-02-20 22:37
Yes, I can build from master now. It even works with the official `jsoncpp` package. When I tried this earlier, various functions could not be linked. I will submit a pull request with the updated instructions for Arch Linux.

Thanks for looking into it!

**Comment by sebjameswml** [comment] 2020-02-21 09:39
Closing, as @tindzk reports success.

**Closed by sebjameswml** 2020-02-21 09:39 UTC

**Comment by NGStaph** [comment] 2021-04-29 00:05
Hi? Are the instructions for arch up to date? I haven't been able to reliably build morphologica on arch. I'm currently using WSLg, but I'd like to know how I could build this on arch for when I make the switch.

**Comment by sebjameswml** [comment] 2021-04-29 06:59
Hi, 

Since @tindzk documented the build process for Arch Linux, all of morphologica (except for a couple of bits of deprecated code) is now header only. So building morphologica is now only necessary to run the test programs and examples, but to build a program *with* morphologica, you only really need to clone it into your own code base and make sure you include its headers. However, it's important to be able to build it to see what it can do.

Because of the changes (from compiling into a dynamically linked library to being a header-only library), it's possible that Tim's Arch Linux installation documentation needs tweaking plus I expect that the Arch Linux/docker build script is now out of date. I'm going to install Arch on a spare disk and have a look, though it won't be today.

Regarding the specific point of jsoncpp - there seems to be a jsoncpp package for Arch: https://archlinux.org/packages/extra/x86_64/jsoncpp/ In fact, @tindzk wrote that the only dependency not available for Arch is Armadillo: https://github.com/ABRG-Models/morphologica/blob/main/README.install.linux.md#package-managed-dependencies-for-arch-linux and you use something called AUR to install it.

I'm pretty confident that if you get the dependencies installed, then morphologica should build correctly with the usual cmake build process.

Let me know if you have any more trouble. I'd also love to know what you have planned for morphologica and how you heard about it :)

Seb

**Comment by NGStaph** [comment] 2021-04-29 17:07
Thank you for your response, 
Ill try building morphologica again and I'll let you know. I'm a student at @Sheffield and have been instructed to refer to this project for my dissertation.

**Comment by sebjameswml** [comment] 2021-04-30 13:09
Ok, I hope it works. Out of interest, how did it go with WSLg? Do the graphical programs work? I've not tried building on WSLg - when I heard about it, I guess I assumed that OpenGL probably still wouldn't be supported, but perhaps it is.

I had a look at installing Arch. To be honest, my heart sank a bit as it's a drawn out process! I feel I got all that out of my system a few years ago with many Gentoo and Linux-from-scratch builds, and now I just use a nice easy Linux like Debian or Ubuntu! However, when I've got a couple of hours spare, I still plan to do an Arch install.

**Comment by NGStaph** [comment] 2021-04-30 23:44
Debian is really easier that way, i'll let you know as soon as i get it running on Arch. 
On windows developer builds (opt-in via settings) windows has added a built-in way to run graphical applications, a simple `wsl --install` command and the instuctions for ubuntu are all you need to build morphologica.

**Comment by sebjameswml** [comment] 2021-06-02 15:09
Sorry - I missed your message from last month. Thanks for the extra info - it's good to know it seems to work on WSL.
